query UserAuctions($creator: String!) {
	auctions(creator: $creator) {
		auctionType
		ended
		startTime
		id
		winningBid {
			amount
			bidder
			timestamp
		}
		auctionData {
			... on EnglishAuction {
				bidCount
				endTime
			}
			... on DutchAuction {
				decayRate
				minPrice
				startPrice
			}
			... on BlindFirstPriceAuction {
				endTime
				revealTime
				revealedBidCount
				sealedBidCount
			}
			... on BlindSecondPriceAuction {
				endTime
				revealTime
				revealedBidCount
				sealedBidCount
			}
		}
	}
}
