query HomePage {
	# TODO use banner auctions
	auctions(onlyLive: true, count: 10) {
		auctionType
		ended
		startTime
		id
		nft {
			name
			imgUrl
			idx
			collection {
				name
				address
				floorPrice
			}
		}
		winningBid {
			amount
			bidder
			timestamp
		}
		auctionData {
			... on EnglishAuction {
				bidCount
				endTime
			}
			... on DutchAuction {
				decayRate
				minPrice
				startPrice
			}
			... on BlindFirstPriceAuction {
				endTime
				revealTime
				revealedBidCount
				sealedBidCount
			}
			... on BlindSecondPriceAuction {
				endTime
				revealTime
				revealedBidCount
				sealedBidCount
			}
		}
	}

	topBids(count: 10) {
		amount
		bidder
		timestamp
		auction {
			id
			auctionType
			nft {
				idx
				imgUrl
				name
				collection {
					address
				}
			}
		}
	}
}
