query UserBids($address: String!) {
	userBids(address: $address) {
		amount
		auction {
			auctionType
			nft {
				name
				idx
				imgUrl
				collection {
					address
					floorPrice
					name
				}
			}
		}
		bidder
		timestamp
	}
}
